apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaappdeployment
  labels:
    app: javaapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        image: srinivasvemula/simapleimage
        ports:
        - containerPort: 8090

